markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: true
gems:
  - jjekyll-relative-links
  - jekyll-wikirefs
plugins:
  - jekyll-relative-links
  - jekyll-wikirefs
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - 3.1 Matrix Operations.md
  - 3.2 Matrix Algebra.md
exclude:
  - vendor
  - node_modules

theme: jekyll-theme-tactile